### ISSUE TITLE
Iteration Progress 19.06.17 !!!필독!!!

### ISSUE THREAD

**Issue by chphch** [swpp-letsstudy/frontend#52]
# !!!Requisites!!!
- [x] Requirement & specification doc 한상준 [[4조] Requirements and Specifications.pdf](https://github.com/swpp-letsstudy/frontend/files/3297260/4.Requirements.and.Specifications.pdf)
- [ ] Final Report 장원이 전창민 정현우 한상준
- [ ] Final Poster 장원이 전창민 정현우 한상준

# Features
- [ ] Improve chatting 정현우
- [ ] Create meetings automatically 장원이
- [x] Add Functions on Meeting Page 전창민
- [x] Create Policy Function 전창민
- [x] Add Sign out Function 전창민
- [x] Create Setting Page 전창민
- [x] Rearrange Policy Page, Notice Page 한상준

# Design
- [x] Mobile design 한상준
- [x] Redesign Main Page, Group Page 한상준
- [x] Design Cloud Storage, Setting Page 한상준
- [x] Design Responsible Page 한상준

# Test Codes
- [x] Additional frontend test codes 장원이
- [x] Additional backend test codes 장원이
- [x] Create test seed  장원이

# Infra / Deploy
- [x] DNS 정현우
- [x] SSL 정현우
- [x] CloudFront 정현우
- [x] frontend: S3 정현우
- [ ] backend: Elastic Beanstalk 정현우

# Test Results

## Frontend
<img width="821" alt="스크린샷 2019-06-17 오후 11 41 18" src="https://user-images.githubusercontent.com/15937757/59613274-9afe8880-9159-11e9-92d1-32708b311cb8.png">
<img width="821" alt="스크린샷 2019-06-17 오후 11 41 28" src="https://user-images.githubusercontent.com/15937757/59613278-9e920f80-9159-11e9-9758-182599d9756e.png">
<img width="821" alt="스크린샷 2019-06-17 오후 11 41 42" src="https://user-images.githubusercontent.com/15937757/59613301-a651b400-9159-11e9-828f-79bffb8aec84.png">
<img width="821" alt="스크린샷 2019-06-17 오후 11 43 31" src="https://user-images.githubusercontent.com/15937757/59613342-bf5a6500-9159-11e9-95bc-0585f19e346e.png">

## Backend
<img width="582" alt="스크린샷 2019-06-17 오후 11 59 09" src="https://user-images.githubusercontent.com/15937757/59614581-00ec0f80-915c-11e9-9c1b-7df60c7357cb.png">
<img width="582" alt="스크린샷 2019-06-17 오후 11 59 23" src="https://user-images.githubusercontent.com/15937757/59614583-02b5d300-915c-11e9-932b-7c7d45005330.png">

**Comment by JangWony** [comment]
그룹 탈퇴나, 삭제 시  다시 한번 물어보는 팝업을 추가하면 좋을 것 같습니다.  물론 우선순위는 낮습니다.

**Comment by chphch** [comment]
@JangWony 좋습니다
개발 가능한 항목들 생각날때마다 아래에 쭉 달아놓고 중요한것부터 하나씩 해보죠

**Comment by sangjunhan** [comment]
벌금계산기능, 그룹 만들 때 policy 선택 기능
